torchrun --nproc_per_node=8 run_vl_classification.py \
  --model_name_or_path /SHARE/liuchonghan/Qwen2-VL-2B-Instruct \
  --train_file /liuchonghan/Multimodal_Search/cifar10_processed/train.json \
  --validation_file /liuchonghan/Multimodal_Search/cifar10_processed/test.json \
  --label_file /liuchonghan/Multimodal_Search/cifar10_processed/labels.json \
  --output_dir /liuchonghan/Multimodal_Search/output/classification_model \
  --num_train_epochs 3 \
  --per_device_train_batch_size 2 \
  --per_device_eval_batch_size 2 \
  --gradient_accumulation_steps 4 \
  --learning_rate 5e-5 \
  --warmup_ratio 0.1 \
  --weight_decay 0.01 \
  --logging_steps 10 \
  --evaluation_strategy "steps" \
  --eval_steps 100 \
  --save_strategy "steps" \
  --save_steps 100 \
  --load_best_model_at_end True \
  --metric_for_best_model "combined_score" \
  --save_total_limit 3 \
  --do_train \
  --do_eval \
  --bf16 \
  --overwrite_output_dir \
  --report_to wandb